### PR TITLE
first change

### PR DESCRIPTION
**Pull request by EunkuBae**
footer

### CODE REVIEW

**Comment by WaKeMaTTa** [comment]
Poor @KingFelix is always geting this kind of Pull Requests. :joy_cat:

**Review by WaKeMaTTa — CHANGES_REQUESTED** [review]
@EunkuBae change your Pull Request base branch:
Screenshot from 2019-05-13 15-39-23

**Comment by KingFelix** [comment]
Hi @EunkuBae,  your commits looks like a blog's personalization. If you are working on a new blog You must fork the repo and then make there the changes you need.

**Comment by EunkuBae** [comment]
Thank you for your response and apology for the pull request. My mistake.
I am figuring out how to personalize the blog(page?).

2019년 5월 13일 (월) 오후 11:22, Jacopo Rabolini <notifications@github.com>님이 작성:

**Pull request closed without merging**
